# templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  # echo -n "mysecretpassword" | base64
  password-encoded: bXlzZWNyZXRwYXNzd29yZA==
---
# templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: {{ .Release.Namespace }}
data:
  # Значения, которые нужны твоему Python APP
  DATABASE_HOST: "service-postgres" # Имя сервиса!
  DATABASE_PORT: "5432"
  DATABASE_USER: "postgres"         # Логин
  DATABASE_NAME: "guestbook"        # Имя БД
